variables:
  - name: agent_pool
    value: "Azure Pipelines"
  - name: image_label
    value: "ubuntu-latest"
  - group: terraform

jobs:
  - job: set_variables
    pool:
      name: $(agent_pool)
      vmImage: $(image_label)
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[task.setvariable variable=first]eh?"
            echo "##vso[task.setvariable variable=second]second"
      - template: templates/use-variables.yml
        parameters:
          variables:
            - $(first)
            - ${{ variables.second }}
            - ${{ format('{0}', variables.first) }}
  - job: explore
    pool:
      name: k8s-ci
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            which helm
            which kubectl
            pwd
            whoami
            curl -sSL https://istio.io/downloadIstio | ISTIO_VERSION=1.6.5 sh -
            ls