variables:
  - name: agent_pool
    value: "Azure Pipelines"
  - name: image_label
    value: "ubuntu-latest"
  - group: terraform

jobs:
  - job: set_variables
    pool:
      name: $(agent_pool)
      vmImage: $(image_label)
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[task.setvariable variable=first]eh?"
            echo "##vso[task.setvariable variable=second]second"
      - template: templates/use-variables.yml
        parameters:
          variables:
            - $(first)
            - ${{ variables.second }}
            - ${{ format('{0}', variables.first) }}
  - job: explore_hosted_agents
    pool:
      name: $(agent_pool)
      vmImage: $(image_label)
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            whoami
            which java
            echo $PATH
            echo $(Agent.ToolsDirectory)
  - job: explore_self_hosted
    pool:
      name: k8s-ci
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            whoami
            which java
            echo $PATH
            echo $(Agent.ToolsDirectory)
