pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
     - script: echo "##vso[task.setvariable variable=valno;isOutput=true]no"
       name: printvar


- stage: depNETrue
  condition: and(succeeded(), ne(dependencies.A.outputs['A1.printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run



- stage: depEQFalse
  condition: and(succeeded(), eq(dependencies.A.outputs['A1.printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: should skip


- stage: depNEFalse
  condition: and(succeeded(), ne(dependencies.A.outputs['A1.printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should skip


- stage: depEQTrue
  condition: and(succeeded(), eq(dependencies.A.outputs['A1.printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run


## Below here try to use stage stageDependencies

- stage: stgdepNETrue
  condition: and(succeeded(), ne(stageDependencies.A.outputs['A1.printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run


- stage: stgdepEQFalse
  condition: and(succeeded(), eq(stageDependencies.A.outputs['A1.printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should skip


- stage: stgdepNEFalse
  condition: and(succeeded(), ne(stageDependencies.A.outputs['A1.printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should skip


- stage: stgdepEQTrue
  condition: and(succeeded(), eq(stageDependencies.A.outputs['A1.printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run

#below here they use the documented syntax from https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies
#but it does not work at all...it's always skipped

- stage: ShouldRunDependenciesEQDocumentedSyntax
  condition: and(succeeded(), eq(dependencies.A.A1.outputs['printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run

- stage: ShouldSkipDependenciesEQDocumentedSyntax
  condition: and(succeeded(), eq(dependencies.A.A1.outputs['printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should skip

- stage: ShouldRunStgdepEQDocumentedSyntax
  condition: and(succeeded(), eq(stageDependencies.A.A1.outputs['printvar.valno'], 'no'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should run

- stage: ShouldSkipStgdepEQDocumentedSyntax
  condition: and(succeeded(), eq(stageDependencies.A.A1.outputs['printvar.valno'], 'yes'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo should skip
